name: yemen_market_app
description: "Professional Marketplace for Yemen"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  fl_chart: ^0.66.2
  hive_flutter: ^1.1.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  speech_to_text: ^6.6.2
  image_picker: ^1.1.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.6.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.5

dev_dependencies:
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  fl_chart: ^0.66.2
  hive_flutter: ^1.1.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  speech_to_text: ^6.6.2
  image_picker: ^1.1.2
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.6.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
