name: yemen_market_app
description: "Professional Marketplace for Yemen"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.0
  fl_chart: ^0.66.2
  hive_flutter: ^1.1.0
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^20.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
