name: yemen_market_app
description: "Professional Marketplace for Yemen"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  fl_chart: ^1.1.1
  hive_flutter: ^1.1.0
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.2
  image_picker: ^1.1.2
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
